// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7rqceXaxO4S04nSggz9pC5WNUPlQgJc',
    appId: '1:363960307698:web:a7c79be219be56cd94656b',
    messagingSenderId: '363960307698',
    projectId: 'safesteer-3b5e6',
    authDomain: 'safesteer-3b5e6.firebaseapp.com',
    databaseURL: 'https://safesteer-3b5e6-default-rtdb.firebaseio.com',
    storageBucket: 'safesteer-3b5e6.appspot.com',
    measurementId: 'G-8VXRJX7D0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCws0J5HBAACiOxW-hqsiVZ6AJhK7YTk0',
    appId: '1:363960307698:android:4551473b6cc16de494656b',
    messagingSenderId: '363960307698',
    projectId: 'safesteer-3b5e6',
    databaseURL: 'https://safesteer-3b5e6-default-rtdb.firebaseio.com',
    storageBucket: 'safesteer-3b5e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAScAxcoR8QFkIq93NlZaHrawxu74v5kdk',
    appId: '1:363960307698:ios:41e55b0a41cf175d94656b',
    messagingSenderId: '363960307698',
    projectId: 'safesteer-3b5e6',
    databaseURL: 'https://safesteer-3b5e6-default-rtdb.firebaseio.com',
    storageBucket: 'safesteer-3b5e6.appspot.com',
    iosBundleId: 'com.example.safeSteer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAScAxcoR8QFkIq93NlZaHrawxu74v5kdk',
    appId: '1:363960307698:ios:7f6f746bcaa415e594656b',
    messagingSenderId: '363960307698',
    projectId: 'safesteer-3b5e6',
    databaseURL: 'https://safesteer-3b5e6-default-rtdb.firebaseio.com',
    storageBucket: 'safesteer-3b5e6.appspot.com',
    iosBundleId: 'com.example.safeSteer.RunnerTests',
  );
}
